server:
  port: 8070

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: USER-API-GATEWAY
    
  cloud:
    gateway:
      routes:
      - id: USER-ATTENDANCE-CONSUMER
        uri: http://localhost:8085/
        predicates:
        - Path=/attendancedetails/**
      - id: USER-ATTENDANCE-CONSUMER
        uri: http://localhost:8085/
        predicates:
        - Path=/attendancedetail/**
      - id: USER-ATTENDANCE-CIRCUIT-BREAKER
        uri: http://localhost:8086/
        predicates:
        - Path=/api/**
      - id: USER-ATTENDANCE-PRODUCER
        uri: http://localhost:8084/
        predicates:
        - Path=/userapi/**
